- LICENSE
Taken from: https://github.com/redhat-developer/vscode-quarkus/blob/master/LICENSE
> Apache 2.0 License

- README.md
Adds a section on contributing lsp4mp extensions to vscode-microprofile 
> Document external lsp4mp extensions

- src/extension.ts
> Ensure language server is stopped when extension is deactivated

- README.md
> Add gitter link to readme

- CHANGELOG.md
Add CHANGELOG 0.1.0
Signed-off-by: azerr <azerr@redhat.com>
> Add CHANGELOG 0.1.0

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/extension.ts
- src/languageServer/requirements.ts
- src/util/javaServerMode.ts
> Update name to Tools for MicroProfile

- src/definitions/constants.ts
- src/extension.ts
Definition support from Java to properties for ConfigProperty/name
See https://github.com/eclipse/lsp4mp/issues/88
Signed-off-by: azerr azerr@redhat.com
> Definition support from Java to properties for ConfigProperty/name

- README.md
- package.json
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Exclude camel.* properties by default #30

- src/extension.ts
> await stop LanguageClient

- .vscode/extensions.json
- .vscode/tasks.json
- package-lock.json
- package.json
- src/test/suite/index.ts
- src/test/suite/languageServer/documentSelectorPlugin.test.ts
- src/test/suite/languageServer/plugin.test.ts
> Fix extension dependencies

- Jenkinsfile
> Allow rgrunber to publish

- CHANGELOG.md
> CHANGELOG for 0.2.0

- .vscode/launch.json
- CHANGELOG.md
- README.md
- USAGE_DATA.md
- package-lock.json
- package.json
- src/extension.ts
Uses redhat.vscode-commons to collect telemetry data.
To see what information is collected, please refer to `USAGE_DATA.md`
Closes #46
> Collect telemetry on extension startup and shutdown

- package-lock.json
> Adjust "resolved" field of package-lock.json.

- package-lock.json
- package.json
> Upversion to 0.3.0

- README.md
- USAGE_DATA.md
- package-lock.json
- package.json
- src/extension.ts
> Update vscode-redhat-telemetry to 0.2.0

- CHANGELOG.md
> Update CHANGELOG for 0.3.0

- package-lock.json
- package.json
> Upversion to 0.3.1

- package-lock.json
- package.json
- Update path-parse from 1.0.6 -> 1.0.7
- Sync versions in package.json & package-lock.json
> Run npm audit fix and make some adjustments

- package.json
Expose the 'microprofile.tools.validation.expression.excluded' settings.
Signed-off-by: azerr <azerr@redhat.com>
> Expose the 'microprofile.tools.validation.expression.excluded' settings.

- package-lock.json
- package.json
> Update vscode-redhat-telemetry to 0.4.2

- CHANGELOG.md
> Bump Changelog date for 0.4.0 Release.

- package-lock.json
- package.json
> Upversion to 0.5.0

- Jenkinsfile
> Replace rsync calls with sftp in Jenkinsfile deployment

- package-lock.json
- Also bump remaining minimist dependencies to 1.2.6
> Bump async from 3.2.1 -> 3.2.3

- package-lock.json
- package.json
- We do not render any EJS templates
> Remove ejs dependency.

- language-support/properties-support/java-properties.tmLanguage.json
Fixes #96 
Signed-off-by: Jessica He <jhe@redhat.com>
> Colorize profile part in application properties

- CHANGELOG.md
> Changelog for 0.5.0

- package-lock.json
- package.json
> Upversion to 0.6.0

- .github/workflows/tests.yml
- Jenkinsfile
> Update node in CI and CD to 14

- CONTRIBUTING.md
> Modify documentation to reflect eclipse/lsp4mp#292

- package.json
- src/languageServer/javaServerStarter.ts
> Disable JVM logging

- language-support/properties-support/microprofile-properties-injections.tmLanguage.json
- language-support/properties-support/microprofile-properties.tmLanguage.json
- package.json
> Adapt to redhat-developer/vscode-java#2636

- package-lock.json
> Fix minimatch vulnerability reported by npm audit

- README.md
> Document Java snippets in the README

- src/extension.ts
- src/util/workspaceUtils.ts
> Only activate vscode-microprofile if a Java project is open

- src/extension.ts
> Fix crash when trying to start in a window with no workspaces

- README.md
> Update documentation for REST snippets

- Jenkinsfile
See https://github.com/redhat-developer/vscode-xml/pull/857
> Use `vsce` from namespace `@vscode`

- package-lock.json
- package.json
- src/languageServer/requirements.ts
Fixes #140 
Signed-off-by: Jessica He <jhe@redhat.com>
> Migrate from find-java-home to jdk-utils

- src/extension.ts
See https://github.com/redhat-developer/vscode-quarkus/pull/589
> Fix requests failing on startup

- src/extension.ts
Fixes the following bugs:
- Some code actions would error out instead of applying
- Some code actions would have an unknown id, despite being given an id on the language server side
- Code actions weren't properly linked to the error they fix
> Fix CodeAction telemetry

- package-lock.json
- package.json
- src/extension.ts
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> Update vscode-redhat-telemetry to 0.6.1

- CHANGELOG.md
- package-lock.json
- package.json
> Changelog for 0.7.1

- src/extension.ts
- src/yaml/YamlSchema.ts
> Initiate YAML schema registration only when YAML file is open or created

- package-lock.json
- package.json
- src/extension.ts
- src/test/runTest.ts
Quick fix not being applied
Fixes #171
> Quick fix not being applied

- package-lock.json
- package.json
> Upversion to 0.12.0

- .github/workflows/tests.yml
- Jenkinsfile
- package-lock.json
- package.json
> Update to NodeJS 18

- package-lock.json
> Bump follow-redirects

- .github/workflows/release.yml
- Remove unnecessary environment variables
- Remove unnecessary --skip-duplicate
> Fix tests for release workflow.

- .github/workflows/release.yml
> Update NodeJS in CD pipeline to NodeJS 20

- CHANGELOG.md
> Update date to 22 october

- .github/workflows/release.yml
> Use Java 21 in build

- README.md
- src/languageServer/requirements.ts
> Extension requires Java 21

- .github/dependabot.yaml
> Reduce frequency of dependabot to Tuesday/Thursday

- .github/dependabot.yaml
This is part of fixing issue at https://github.com/dependabot/dependabot-core/issues/12209#issuecomment-2872582146 ,
This PR adds double quotes ("") around property values.
> Updates dependabot.yml file as per standards
