- package.json
Updates `displayName` and `description` in package.json to `MicroProfile Tools` to match the name used in changelog/extension settings/messages 
Also adds `Snippets` to categories since lsp4mp provides microprofile snippets.
> Update extension displayName to MicroProfile Tools

- package.json
- schemas/package.schema.json
- src/extension.ts
- src/languageServer/javaServerStarter.ts
- src/languageServer/plugin.ts
- src/test/resources/quarkus-package.json
- src/test/suite/languageServer/documentSelectorPlugin.test.ts
- src/test/suite/languageServer/plugin.test.ts
Fixes #3 
Signed-off-by: David Kwon <dakwon@redhat.com>
> Remove quarkus-properties language and collect document selectors from extensions

- language-support/properties-support/java-properties.tmLanguage.json
`#` only works if its not the first character in the property name.
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/283
> Allow `[`, `]`, and `#` in property keys TextMate grammar

- src/extension.ts
- src/util/javaServerMode.ts
Fixes #12 
Detects if java ls started in lightweight mode and prompts user to switch to standard. The user ends up getting a second prompt from vscode-java to ask if they are sure.
> Detect lightweight java language server

- src/util/javaServerMode.ts
Switch java server mode prompt was missing a space. So it showed up as:
`... in Standard mode.Do you want to switch ...`
> Fix missing space in switch java mode prompt

- README.md
- package.json
You can now set the severity of diagnostics related to references to unknown properties using `microprofile.tools.validation.expression.severity`.
Requires the server-side changes in https://github.com/eclipse/lsp4mp/pull/21
> Add new setting for property expression validation

- README.md
- package.json
- Resolves redhat-developer/vscode-quarkus#314 
I'll need to test this out to confirm it works correctly, but this seems to be the right thing.
> Ignore kafka-streams namespace by default.

- src/languageServer/plugin.ts
- Fixes #26
I think most extensions do a simple string comparison in this part of the code but it seems the MicroProfile contribution has more structure.
> Use isDeepStrictEqual for MicroProfileContribution comparison.

- .eslintrc.json
- src/extension.ts
- src/providers/microProfileCompletionItemProvider.ts
- src/providers/microProfileProviders.ts
Improve the performance for completion in java files by directly consuming the output of the jdt.ls extension, instead of having the requests and results forwarded through the MicroProfile language server.
See eclipse/lsp4mp#129
> Directly consume the completion from the jdt.ls extension

- package-lock.json
- src/extension.ts
Added support for 'shouldLanguageServerExitOnShutdown' capability, which means that the language server shuts down when shutdown is received instead of when exit is received.
Closes #69 
Signed-off-by: Alexander Chen alchen@redhat.com
> Support 'shouldLanguageServerExitOnShutdown' capability

- package.json
[MP Config 2.0] Support for config profiles
See https://github.com/eclipse/lsp4mp/issues/78
Signed-off-by: azerr <azerr@redhat.com>
> [MP Config 2.0] Support for config profiles

- .github/workflows/tests.yml
- Jenkinsfile
```
+npm WARN notsup Unsupported engine for vsce@2.1.0: wanted: {"node":">= 14"} (current: {"node":"12.13.1","npm":"6.12.1"})
+npm WARN notsup Not compatible with your version of node/npm: vsce@2.1.0
+
++ vsce@2.1.0
```
Note : In the GH actions yaml, I went with `@1.103.1` instead of `@<2` because we also run the build on Windows and PowerShell doesn't seem to support that format. There might be some special way to escape it so it works but for now we can just list the value as-is.
> Use vsce 1.x since 2.x is not compatible with Node 12.x

- package-lock.json
- package.json
- Fixes #81
- Update find-java-home to benefit from fix that correctly resolves
relative symbolic links
> Update to find-java-home 1.2.2

- README.md
- src/extension.ts
- src/languageServer/javaServerStarter.ts
- src/languageServer/requirements.ts
- src/util/javaServerMode.ts
- Fixes #84
- Use 'redhat.java' embedded JRE through RequirementsData from its
ExtensionAPI
- Adjust README with new requirements
> Use embedded JRE from redhat.java to launch language server.

- package-lock.json
- package.json
- Update follow-redirects 1.14.7 to 1.14.8
- Update mocha 9.1.3 to 9.2.0 for nanoid issue
> Update follow-redirects and mocha

- Jenkinsfile
> Use ovsx<0.3.0 to ensure we build with Node v12.

- language-support/properties-support/java-properties.tmLanguage.json
Fixes redhat-developer/vscode-quarkus#272
Signed-off-by: Jessica He <jhe@redhat.com>
> Added textmate grammar support for property expressions

- README.md
- package-lock.json
- package.json
- src/extension.ts
- src/providers/microProfileProviders.ts
- src/providers/microprofileInlayHintsProvider.ts
Display property expression evaluation as inlay hint
See https://github.com/eclipse/lsp4mp/issues/226
Signed-off-by: azerr <azerr@redhat.com>
> Display property expression evaluation as inlay hint

- gulpfile.js
- package.json
Modifies the script that builds the JDT.LS extension in order to adapt to the inclusion of smallrye-common-expression and a custom target platform in lsp4mp.
Requires eclipse/lsp4mp#283
> Include smallrye-common-expression bundles

- src/definitions/microProfileLSRequestNames.ts
- src/extension.ts
See eclipse/lsp4mp#171 and eclipse/lsp4mp#299
> Provide binding for CodeAction resolve

- README.md
- USAGE_DATA.md
- package-lock.json
- package.json
this brings 2 features:
- VS Code's own `telemetry.telemetryLevel` setting takes precedence over `redhat.telemetry`
- allows remote configuration of telemetry (to disable events). https://github.com/redhat-developer/vscode-redhat-telemetry#remote-configuration
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> Update vscode-redhat-telemetry to 0.5.2

- src/extension.ts
Pass the cancellation token from the microprofile-ls request onto the delegate command invocation, so that if microprofile-ls cancels the request, then the delegate command gets canceled.
> Support cancelling delegate commands

- USAGE_DATA.md
- src/definitions/commands.ts
- src/extension.ts
- src/util/telemetry.ts
- Send telemetry every time a quick fix or source action is applied
- Use the new code action id field introduced in https://github.com/eclipse/lsp4mp/pull/371 to identify the type of code action in the telemetry message so that we can gauge usage of each code action
Requires https://github.com/eclipse/lsp4mp/pull/371
> Telemetry for code actions

- gulpfile.js
All jars passing through `gulp.src` are corrupted. I noticed that pre-release bulds were failing for vscode-quarkus & vscode-microprofile. When I examined the actual logs, I was seeing :
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2024-05-02 16:27:12.411
!MESSAGE Failed to load extension bundles
!STACK 1
org.eclipse.core.runtime.CoreException: Load bundle list
at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:173)
...
...
Contains: Cannot extract bundle symbolicName or version /home/rgrunber/.vscode/extensions/redhat.vscode-microprofile-0.12.2024041608/jars/org.eclipse.lsp4mp.jdt.core.jar
java.util.zip.ZipException: zip END header not found
at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
at …
```
> Set encoding as false for gulp.src to treat content as binary.

- .github/workflows/release.yml
- Improve naming of the 'release' workflow.
@angelozerr , Let me know if the name works for you. This will also handle post-release bumps, simplifying the release instructions. I can do the same for vscode-quarkus and any other vscode extensions we release. `pm version --no-git-tag-version patch` makes it really easy!
> Implement post-release version bump.

- CHANGELOG.md
> chore: CHANGELOG for 0.13.0

- CONTRIBUTING.md
Fixes #385 
Changes to Eclipse require JDK 21 or higher to build the extension part of this project.
Also, a change to LSP4MP no longer requires removing a certain line in `org.eclipse.lsp4mp.jdt.target` file starting with `<location·type="Target"`
> fix : Update the Development Setup to state JDK 21+ and remove LSP4MP location target line

- .github/dependabot.yaml
It only accepts a 5 part expression, and I supplied a 7 part one.
> Fix dependabot cron expression

- .github/dependabot.yaml
- Remove typescript-eslint group; it's unused
> Group eslint dependencies together
